<template>
  <div class="section">
    <div class="content">
      <h1>Privacy and Policy</h1>
      <p>Learn more about privacy and policy on this website</p>
      <h2>Data / Information Privacy / Confidentiality</h2>
      <p>
        The first party will store, manage, data or information needed from both
        the second party and third party. The first party uses sensitive data
        such as COOKIE generated by users that will be shared into other
        services such as Facebook, Google, Google Analitycs, Google Tag Manager
        The first party has the right to give part or all of the information to
        shareholders, employees and others who have agreed and cooperated with
        the first party The first party is not responsible if there is a data
        leak either caused by technical or non-technical errors Candidates for
        the second party are considered conscious and without any coercion when
        registering to become a second party.
      </p>
      <h2>Use of Trademarks / Copyrights / Brands</h2>
      <p>
        The first party does not feel that he has the use of any trademarks,
        trademarks, copyrights, or brands that are managed by second parties,
        third parties or outside parties. If the first party is proven to have
        committed a violation or it is indicated that there was a violation
        committed by the first party, the second party or a third party. Can
        directly contact the administrator for further action.
      </p>
      <h2>Dispute</h2>
      <p>
        If there is a dispute it will be done in a family way
      </p>
      <h2>Change of Rules</h2>
      <p>
        The first party has the right to change these rules without prior
        notice.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  layout: 'default',
  data (){
    return {
      name: 'Cenah.co.id',
      suffix: ' - Cenah.co.id',
      title: 'Privacy and Policy',
      description: 'Learn more about Privacy and Policy at cenah.co.id company profile website.'
    }
  },
  head() {
    return {
      title: this.title+this.suffix,
      meta: [
        {
          hid: 'description',
          name: 'description',
          content: this.description
        },
        {
          hid: 'og:title',
          name: 'og:title',
          content: this.name+': '+this.title
        },
        {
          hid: 'og:description',
          name: 'og:description',
          content: this.description
        }
      ]
    }
  }
}
</script>
